[package]
authors = ["Yogx Astawan <yogi.astawan@gmail.com>"]
name = "gx_md"
version = "0.1.0"
edition = "2021"
description = "Minimal documentation for C language"
license = "MIT"
repository = "https://github.com/yogiastawan/gx_md"

[dependencies]
